container:
  image: golang:latest

test_task:
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  get_script: go get ./...
  build_script: go build ./...
  test_script: |
    go install gotest.tools/gotestsum@latest
    curl --location --fail-with-body --no-progress-meter https://github.com/go-task/task/releases/download/v3.39.2/task_linux_amd64.tar.gz -o task_linux_amd64.tar.gz
    tar xzf task_linux_amd64.tar.gz
    ./task check-coverage

lint_task:
  container:
    image: golangci/golangci-lint:latest
  run_script: golangci-lint run
